language:
  - python
matrix:
  include:
    - os: linux
      python: 3.6
      dist:
        - bionic
        - xenial
    - os: osx
      python: 3.6
install:
  - pip install -r ./requirements/development.txt
script:
  - nosetests -v
