language:
  - python
matrix:
  include:
    - os: linux
      python:
        - "3.6"
install:
  - pip install -r ./requirements/development.txt
services:
  - postgresql
addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.3
before_script:
  - psql -c 'CREATE DATABASE testing_arith_io;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d testing_arith_io
script:
  - tox
deploy:
  provider: pypi
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
